version: '3'
services:
  connector-blacklistip:
    build: .
    environment:
      # Connector's definition parameters:
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=${CONNECTOR_NAME}
      - CONNECTOR_SCOPE=Incident
      # Connector's generic execution parameters:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_ID}
      - CONNECTOR_CONFIDENCE_LEVEL=${CONNECTOR_CONFIDENCE_LEVEL} # From 0 (Unknown) to 100 (Fully trusted).
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_LOG_LEVEL}
      - CONNECTOR_RUN_EVERY=${CONNECTOR_RUN_EVERY}
      # Connector's custom execution parameters:
      - EXTRA_PARAMETER=${EXTRA_PARAMETER}
      # Add proxy parametrs below if you need them
      # - HTTP_PROXY=ChangeMe
      # - HTTPS_PROXY=ChangeMe
      # - NO_PROXY=ChangeMe
    restart: always
    networks:
      - opencti_stack_v1_default

networks:
  opencti_stack_v1_default:
    external: true
