version: '3'
services:
  connector-blacklistIP:
    build: .
    environment:
      # Connector's definition parameters:
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=${CONNECTOR_NAME}
      - CONNECTOR_SCOPE=Incident
      # Connector's generic execution parameters:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_ID}
      - CONNECTOR_CONFIDENCE_LEVEL=${CONNECTOR_CONFIDENCE_LEVEL} # From 0 (Unknown) to 100 (Fully trusted).
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_LOG_LEVEL}
      - CONNECTOR_RUN_EVERY=${CONNECTOR_RUN_EVERY}
      # Connector's custom execution parameters:
      - EXTRA_PARAMETER=${EXTRA_PARAMETER}
      - HTTP_PROXY=http://10.32.156.23:3128
      - HTTPS_PROXY=http://10.32.112.11:3128
      - NO_PROXY=localhost,10.32.150.162,127.0.0.1,docker-registry.example.com,.corp,opencti
    restart: always
    networks:
      - opencti_stack_v1_default

networks:
  opencti_stack_v1_default:
    external: true