opencti:
  url: 'http://localhost:8080'
  token: 'ChangeMe'

connector:
  id: 'ChangeMe'
  type: 'EXTERNAL_IMPORT'
  name: 'blacklistIP'
  scope: 'attack-pattern' # MIME type or SCO
  confidence_level: 100 # From 0 (Unknown) to 100 (Fully trusted)
  log_level: 'info'
  update_existing_data: false
  run_and_terminate: false

blacklistIP:
  interval: 1 # in days
  url: 'http://api.blocklist.de/getlast.php?time='
